import { describe, expect, it } from 'vitest';
import { rowAtDay, runIssueBurnSimulation, solveRequiredFtes } from './engine';
import { referenceScenarioInput } from './fixtures/referenceCalculatorBaseline';

/**
 * Calculator parity tests.
 *
 * Expected values were produced by extracting the reference calculator's
 * own `simulate()` function (go_live_recovery_calculator_client.html, no
 * DOM) and running it in Node against the exact same baseline data — same
 * technique as the estimation engine's calculator-parity tests.
 */
describe('runIssueBurnSimulation — reference calculator parity', () => {
  it('matches the reference calculator baseline end-to-end', () => {
    const result = runIssueBurnSimulation(referenceScenarioInput());
    expect(result.clearDay).toBe(36);
    expect(result.capacityPerDay).toBeCloseTo(6, 6);
    expect(result.totalIssueWork).toBeCloseTo(151.8, 6);
  });

  it('matches cumulative row values at representative days', () => {
    const result = runIssueBurnSimulation(referenceScenarioInput());
    expect(rowAtDay(result, 1)).toMatchObject({ executedCumulative: 20, generatedCumulative: 4, reopenedCumulative: 0 });
    expect(rowAtDay(result, 5)).toMatchObject({ executedCumulative: 100, generatedCumulative: 20 });
    expect(rowAtDay(result, 5).reopenedCumulative).toBeCloseTo(3.6, 6);
    expect(rowAtDay(result, 5).backlog).toBeCloseTo(20.7, 6);
    expect(rowAtDay(result, 10)).toMatchObject({ executedCumulative: 200, generatedCumulative: 40 });
    expect(rowAtDay(result, 10).backlog).toBeCloseTo(15.2, 6);
    expect(rowAtDay(result, 20)).toMatchObject({ executedCumulative: 400, generatedCumulative: 80 });
    expect(rowAtDay(result, 20).backlog).toBeCloseTo(4, 6);
    const day28 = rowAtDay(result, 28);
    expect(day28.influxAddedToday).toBe(20);
    expect(day28.executedCumulative).toBeCloseTo(449.57632, 4);
    expect(day28.backlog).toBeCloseTo(20, 4);
    expect(rowAtDay(result, 35)).toMatchObject({ executedCumulative: 450, generatedCumulative: 90 });
    expect(rowAtDay(result, 35).backlog).toBeCloseTo(0, 6);
    expect(rowAtDay(result, 35).remaining).toBe(0);
  });
});

describe('runIssueBurnSimulation — toggleable levers', () => {
  it('disabling execution-driven issues stops new issues from being generated by testing', () => {
    const input = referenceScenarioInput({
      levers: {
        ...referenceScenarioInput().levers,
        executionDrivenIssues: { enabled: false, casesPerIssue: 5 },
        issueInfluxEvents: { enabled: false, events: [] },
        reopenRate: { enabled: false, reopenRatePercent: 15 },
      },
    });
    const result = runIssueBurnSimulation(input);
    expect(result.totalGenerated).toBe(0);
    // Starting backlog (22) still resolves at capacity 6/day, unblocked by any new issues,
    // and execution still proceeds to completion since blocked cases still throttle it.
    expect(result.totalIssueWork).toBe(22);
  });

  it('disabling blocked-case throttling lets execution run at full steady-state pace', () => {
    const input = referenceScenarioInput({
      levers: { ...referenceScenarioInput().levers, blockedCaseThrottling: { enabled: false, blockedCasesPerIssue: 2 } },
    });
    const result = runIssueBurnSimulation(input);
    // 450 cases at 20/day with no throttling clears execution in exactly 23 workdays.
    expect(rowAtDay(result, 23).remaining).toBe(0);
    expect(rowAtDay(result, 23).blocked).toBe(0);
  });

  it('disabling reopen rate stops resolved issues from reopening', () => {
    const input = referenceScenarioInput({
      levers: { ...referenceScenarioInput().levers, reopenRate: { enabled: false, reopenRatePercent: 15 } },
    });
    const result = runIssueBurnSimulation(input);
    expect(result.totalReopened).toBe(0);
  });

  it('disabling issue influx events removes the modeled spike', () => {
    const input = referenceScenarioInput({
      levers: { ...referenceScenarioInput().levers, issueInfluxEvents: { enabled: false, events: [] } },
    });
    const result = runIssueBurnSimulation(input);
    expect(result.totalInflux).toBe(0);
    expect(rowAtDay(result, 28).influxAddedToday).toBe(0);
  });

  it('a zero client review buffer makes newly generated issues immediately eligible', () => {
    const input = referenceScenarioInput({
      levers: {
        ...referenceScenarioInput().levers,
        clientReviewBuffer: { enabled: false, bufferDays: 1 },
        issueInfluxEvents: { enabled: false, events: [] },
      },
    });
    const result = runIssueBurnSimulation(input);
    // With immediate eligibility and enough capacity headroom the backlog never grows
    // past what capacity can absorb on day 1: 22 starting + up to cap resolved same day.
    expect(rowAtDay(result, 1).backlog).toBeLessThan(referenceScenarioInput().startingIssues + 5);
  });

  it('calendar-driven issues add a decoupled arrival rate independent of execution pace', () => {
    const input = referenceScenarioInput({
      totalTestCases: 0, // no execution at all
      startingIssues: 0,
      levers: {
        ...referenceScenarioInput().levers,
        executionDrivenIssues: { enabled: false, casesPerIssue: 5 },
        issueInfluxEvents: { enabled: false, events: [] },
        calendarDrivenIssues: { enabled: true, baseRatePerDay: 3 },
        reopenRate: { enabled: false, reopenRatePercent: 15 },
      },
    });
    const result = runIssueBurnSimulation(input);
    // 3 issues/day arrive purely on the calendar even though there's nothing to execute.
    expect(rowAtDay(result, 4).issueWorkCumulative).toBeCloseTo(12, 6);
  });
});

describe('solveRequiredFtes', () => {
  it('finds the minimum FTE count that clears the queue by the target workday', () => {
    const input = referenceScenarioInput();
    const { recommendedFtes, sensitivity } = solveRequiredFtes(input, { minFtes: 1, maxFtes: 12, step: 0.5 });
    expect(recommendedFtes).not.toBeNull();
    const chosen = sensitivity.find((row) => row.fteCount === recommendedFtes);
    expect(chosen?.onTime).toBe(true);
    // Anything below the recommended count should not be on time.
    const below = sensitivity.filter((row) => row.fteCount < (recommendedFtes ?? 0));
    expect(below.every((row) => !row.onTime)).toBe(true);
  });
});
